; Not Used by Hentairim

[DialogueOptions]
bAllowGreets=1
bKeepLoversTitles=1
fForeplayDuration=6
fPenetrativeSexDuration=7.5
bAllowAttacks=1
iIntensityThreshold=60
iAnalIntensityThreshold=40
iFemaleCloseThreshold=87
iChemistryLevel=10
bAggressiveDialogue=1
iBootyGirls=0
iAnalSurpriseReaction=0
iChanceForAnal=0
bStealthInPublic=0
bStealthInUncleared=0
bNoStealthInDaylight=1
bAllowJokes=1
fSpacingMultiplier=1.2
iAnalAnimationFilter=4
iOKWithVaginalCum=0
bStealthyMaleOrgasm=0
bStealthyFemaleOrgasm=0

[VoiceSystemManagement]
bMuteSexLabVoices=0
bRequireVoiceForBothActors=0
iAllowGroupSex=0
iAllowSoloMasturbation=1
iMasterVolume=100

[FemaleVoices]
sFemale1VoiceType=Empty
sFemale1Actor=Empty
sFemale2VoiceType=Empty
sFemale2Actor=Empty

[MaleVoices]
sMale1VoiceType=Empty
sMale1Actor=Empty
sMale2VoiceType=Empty
sMale2Actor=Empty
sMale3VoiceType=Empty
sMale3Actor=Empty
sMale4VoiceType=Empty
sMale4Actor=Empty
sMale5VoiceType=Empty
sMale5Actor=Empty
sMale6VoiceType=Empty
sMale6Actor=Empty
sMale7VoiceType=Empty
sMale7Actor=Empty
sMale8VoiceType=Empty
sMale8Actor=Empty

[DefaultVoices]
iFemaleDefaultVoice=0
iMaleDefaultVoice=0
iFemaleCreatureDefaultVoice=0
iMaleCreatureDefaultVoice=0

[DoNotTouch]
sVoiceTypeManualEntry=Type Here
sVoiceTypeUnderInspection=Empty
sActorManualEntry=Type Here
sActorUnderInspection=Empty
sTargetActor=None
sTargetVoiceType=Empty
sAssignToTargetActor=Click Here
sSampleVoiceSlot=Sample Audio From Voice Slot
sUnmuteSexLabVoices=Click To Unmute SexLab Voices NOW